/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PawketRouteRouteImport } from './routes/pawket/route'
import { Route as KibbleRouteRouteImport } from './routes/kibble/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PawketIndexRouteImport } from './routes/pawket/index'
import { Route as KibbleIndexRouteImport } from './routes/kibble/index'

const PawketRouteRoute = PawketRouteRouteImport.update({
  id: '/pawket',
  path: '/pawket',
  getParentRoute: () => rootRouteImport,
} as any)
const KibbleRouteRoute = KibbleRouteRouteImport.update({
  id: '/kibble',
  path: '/kibble',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PawketIndexRoute = PawketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PawketRouteRoute,
} as any)
const KibbleIndexRoute = KibbleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KibbleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kibble': typeof KibbleRouteRouteWithChildren
  '/pawket': typeof PawketRouteRouteWithChildren
  '/kibble/': typeof KibbleIndexRoute
  '/pawket/': typeof PawketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kibble': typeof KibbleIndexRoute
  '/pawket': typeof PawketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kibble': typeof KibbleRouteRouteWithChildren
  '/pawket': typeof PawketRouteRouteWithChildren
  '/kibble/': typeof KibbleIndexRoute
  '/pawket/': typeof PawketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kibble' | '/pawket' | '/kibble/' | '/pawket/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kibble' | '/pawket'
  id: '__root__' | '/' | '/kibble' | '/pawket' | '/kibble/' | '/pawket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KibbleRouteRoute: typeof KibbleRouteRouteWithChildren
  PawketRouteRoute: typeof PawketRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pawket': {
      id: '/pawket'
      path: '/pawket'
      fullPath: '/pawket'
      preLoaderRoute: typeof PawketRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kibble': {
      id: '/kibble'
      path: '/kibble'
      fullPath: '/kibble'
      preLoaderRoute: typeof KibbleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pawket/': {
      id: '/pawket/'
      path: '/'
      fullPath: '/pawket/'
      preLoaderRoute: typeof PawketIndexRouteImport
      parentRoute: typeof PawketRouteRoute
    }
    '/kibble/': {
      id: '/kibble/'
      path: '/'
      fullPath: '/kibble/'
      preLoaderRoute: typeof KibbleIndexRouteImport
      parentRoute: typeof KibbleRouteRoute
    }
  }
}

interface KibbleRouteRouteChildren {
  KibbleIndexRoute: typeof KibbleIndexRoute
}

const KibbleRouteRouteChildren: KibbleRouteRouteChildren = {
  KibbleIndexRoute: KibbleIndexRoute,
}

const KibbleRouteRouteWithChildren = KibbleRouteRoute._addFileChildren(
  KibbleRouteRouteChildren,
)

interface PawketRouteRouteChildren {
  PawketIndexRoute: typeof PawketIndexRoute
}

const PawketRouteRouteChildren: PawketRouteRouteChildren = {
  PawketIndexRoute: PawketIndexRoute,
}

const PawketRouteRouteWithChildren = PawketRouteRoute._addFileChildren(
  PawketRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KibbleRouteRoute: KibbleRouteRouteWithChildren,
  PawketRouteRoute: PawketRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
